#!/usr/bin/env python

"""
Git pre-commit hook.
"""

import sys

from vfgithook import githooks, logger


if __name__ == '__main__':
    logger.setup_logger()

    if githooks.precommit_hook():
        sys.exit(0)
    else:
        sys.exit(1)


sys.exit(1)
