#!/usr/bin/env python

"""
Git push update hook.
"""

import sys

from vfgithook import githooks


if __name__ == '__main__':
    if githooks.update_hook(sys.argv[1], sys.argv[2], sys.argv[3]):
        sys.exit(0)
    else:
        sys.exit(1)


sys.exit(1)
